app.run(function($rootScope) {
    $rootScope.ua = 0;
    $rootScope.en = 1;
    $rootScope.ru = 2;
    $rootScope.vers = 1.2;
    console.log('%c VERBAL MATCH VERSION - ' + $rootScope.vers, 'background: #000; color: #00d2dc; font-size:20px;');
    console.log(storage);
    $rootScope.langs = [{
        "APPNAME": "VERBAL MATCH",
        "UA": "UKRAINE",
        "Practice": "Практика",
        "Campaign": "Компанія",
        "Lessons": "Уроки",
        "Info": "Інформація",
        "Settings": "Налаштування",
        "Audio": "Аудіо",
        "Language": "Мова",
        "Worldrank": "Глобальний рейтинг",
        "Localrank": "Локальний рейтинг",
        "PassedLevels": "Пройдені рівні",
        "CurrentLevel": "Поточний рівень",
        "Tipsofaday": "Порада дня",
        "ResultofLevel": "Результат рівня",
        "AllIsFine": "Відмінно!",
        "Earnedpoints": "Зароблено очок",
        "Allpoints": "Всі очки",
        "Requiredfornextlevel": "До наступного рівня",
        "TimeLeft": "Часу лишилося",
        "Restart": "Заново",
        "Nextlevel": "Наступний рівень",
        "Yourlevelis": "Твій рівень",
        "Level": "Рівень",
        "Levelprogress": "Прогрес рівня",
        "Newlevelsappearslater": "Нові рівні появляться пізніше",
        "Timeisover": "Час закінчився",
        "Youlose": "Практикуйся більше!",
        "points": " points",
        "Practicemore": "Більше практикуйся",
        "Currentversion": "Поточна версія",
        "Sounds": "Звуки",
        "Home": "Головна",
        "ISNOTALLOWED": "НЕ ДОСТУПНИЙ",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
    }, {
        "APPNAME": "VERBAL MATCH",
        "EN": "ENGLISH",
        "Practice": "Practice",
        "Campaign": "Campaign",
        "Lessons": "Lessons",
        "Info": "Info",
        "Settings": "Settings",
        "Audio": "Audio",
        "Language": "Language",
        "Worldrank": "World rank",
        "Localrank": "Local rank",
        "PassedLevels": "Passed Levels",
        "CurrentLevel": "Current Level",
        "Tipsofaday": "Tip of a day",
        "ResultofLevel": "Result of Level",
        "AllIsFine": "Perfect!",
        "Earnedpoints": "Earned points",
        "Allpoints": "All points",
        "Requiredfornextlevel": "Required for next level",
        "TimeLeft": "Time Left",
        "Restart": "Restart",
        "Nextlevel": "Next level",
        "Yourlevelis": "Your level is",
        "Level": "Level",
        "Levelprogress": "Level progress",
        "Newlevelsappearslater": "New levels appears later",
        "Timeisover": "Time is over",
        "Youlose": "You lose",
        "points": " points",
        "Practicemore": "Practice more",
        "Currentversion": "Current version",
        "Sounds": "Sounds",
        "Home": "Home",
        "ISNOTALLOWED": "IS NOT ALLOWED",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
    }, {
        "APPNAME": "VERBAL MATCH",
        "RU": "RUSSIAN",
        "Practice": "Практика",
        "Campaign": "Компания",
        "Lessons": "Уроки",
        "Info": "Информация",
        "Settings": "Настройки",
        "Audio": "Aудио",
        "Language": "Язык",
        "Worldrank": "Мировое звание",
        "Localrank": "Местный ранг",
        "PassedLevels": "Пройденные уровни",
        "CurrentLevel": "Текущий уровень",
        "Tipsofaday": "Совет дня",
        "ResultofLevel": "Результат уровня",
        "AllIsFine": "Отлично!",
        "Earnedpoints": "Заработанные очки",
        "Allpoints": "Все очки",
        "Requiredfornextlevel": "Требуется для следующего уровня",
        "TimeLeft": "Осталось времени",
        "Restart": "Повторно",
        "Nextlevel": "Следующий уровень",
        "Yourlevelis": "Твой уровень",
        "Level": "Уровень",
        "Levelprogress": "Прогрес Уровеня",
        "Newlevelsappearslater": "Новые уровни появляются позже",
        "Timeisover": "Время вышло",
        "Youlose": "Иди учись",
        "points": " points",
        "Practicemore": "Больше практиковаться",
        "Currentversion": "Текущая версия",
        "Sounds": "Звуки",
        "Home": "Главная",
        "ISNOTALLOWED": "НЕ ДОПУСКАЕТСЯ",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
        "": "",
    }]
})